spring:
  application:
    name: internship

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JPA_Test
    username: root
    password: root
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true


#spring.datasource:
#  url: jdbc:h2:./internship-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#  username: sa
#  password: sa
server.port: 8081